### PR TITLE
Allow to choose the page of the document to be transformed 

### PR DESCRIPTION
**Pull request by xorti**
in image by setting the static property of the transmuter

Following the PR discussion: https://github.com/alchemy-fr/Media-Alchemyst/pull/30

### CODE REVIEW

**Comment by marclaporte** [comment]
@jygaulier any thoughts?

Thanks!

**Comment by xorti** [comment]
Hello @jygaulier 

Is it possible to merge these changes, and release it under the same version (0.5.3, for example) including also the unoconv changes?

Thank you

**Comment by jygaulier** [comment]
Hi @xorti,
I just released 0.5.3, can you check everything is ok ?
Thank you

**Comment by xorti** [comment]
Hi @jygaulier 

For this issue itself, it is ok. The only thing that is missing in update the https://packagist.org/packages/media-alchemyst/media-alchemyst versions.

---
 Can you please have look to my comment in: 
https://github.com/alchemy-fr/Media-Alchemyst/pull/29#issuecomment-542285707

**Pull request merged**
