### PR TITLE
Fix issue when converting document2image where image only supports 1 …

### PR DESCRIPTION
**Pull request by xorti**
…page

- It allows to select the document page to convert to image

### CODE REVIEW

**Comment by xorti** [comment]
@jygaulier after merge, please release a new version (0.5.4?).

Thanks

**Comment by xorti** [comment]
@nmaillat @jygaulier I've updated the code with the latest changes from master. This will fix an issue introduced in 0.5.3 when using page numbers while exporting document to image, releasing a 0.5.4 with this patch will be appreciated.

**Comment by jygaulier** [comment]
Hi @xorti.
I see that the pr is kind of revert of "allow to choose the page to be exported" which was released as 0.5.3. I think this did not generate bc-break since it was only new methods to change default value (1).
Can you tell us what is your (use)case / issue / version ?
If you need methods "fromPage()" (without 's') and "getPage()", we could simply add those methods without removing the multi-pages ones ?

btw we will soon release a new version 0.5.4 which fix issue related to video orientation, so the "pages" fix will be 0.5.5

**Comment by xorti** [comment]
Hi @jygaulier 

The functionality: "allow to choose the page to be exported" it is still present, we need that feature.

I replaced the fromPages to fromPage because this process only returns 1 image. So, using fromPages and pageQuantity is a bit odd in my perspective.

**The use case**
Let's say that I have a document with 3 pages.
If I want page 2, I have to call `fromPages(2,2)` and that will convert the document to PDF (page 2-2) (one page as output), which is processed after by ghostscript , that's why I reverted the ghostscript transmuter call back to 1,1.

**Issue:**
Using `fromPages (2,3)` would create a PDF document with 2 pages, and later the ghostscript would fail to convert to image correctly because that would be out of bounds (from 2 to 3) where the document had only 2 pages.

Also, the variable names were not correct (sorry for that) pageQuantity is makes confusion. Were we can think on 1 page only, so if we want just page number 2 we would use: fromPages(2,1) and that will create a PDF with range 2-1 and fail to transcode with ghostscript.

**Solution**
If we want multiple images (for different pages) we just need to call `fromPage()` and then invoke the transmuter.

For page 2: `fromPage(2);`
For page 3: `fromPage(3);`

That process will convert document chosen page to image correctly.

Thank you.

v0.5.5 is fine for me.

**Comment by jygaulier** [comment]
@xorti You are right, we did code/merge too fast...
Even if "quantity" was not the best name ("count" is probably better), the pdf conversion wants "pagefrom-pageto", so we forgot at least an addition.
But this is not the deal : Because when reading the previous pr, I focused on a new functionality (allowing to choose the number of pages pdf), I did not see the context/goal : **one image**, pdf is tmp...

so "en résumé" : I will merge right now this "one page only" fix, and release a **0.5.4** (since the "video orientation" is not yet merged).

thank you for "defocussing"
JY

**Pull request merged**
